SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (1, N'أعمال', N'أعمال.jpeg', N'ادخال بيانات ، استشارات اعمال ، تجارة الكترونية ، خدمات قانونية ، خدمات مالية ، خدمات مالية ، دراسات وأبحاث ، مساعد افتراضي ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (2, N'برمجة وتطوير', N'برمجة.jpg', N'أنظمة ادارة محتوى ، سيرفرات ، برمجة CSS و HTML ، برمجة Java و .NET ، برمجة بايثون ، برمجة تطبيقات الجوال ، تطبيقات سطح المكتب ، تطوير متاجر الكترونية ، خدمات ووردبريس ، دعم فني تقني ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (3, N'تسويق الكتروني', N'تسويق الكتروني.png', N'ادارة حسابات التواصل الاجتماعي ، اعلانات المواقع ، استشارات تسويقية ، التسويق بالمحتوى ، التسويق على مواقع التواصل الاجتماعي ، تحليلات المواقع ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (4, N'تدريب', N'تدريب.jpg', N'استشارات شخصية ، صحة ولياقة بدنية ، تعلم البرمجة ، تعلم التسويق ، تعلم التصميم ، تعلم اللغات ، فنون وحرف ، مساعدة بحل الواجبات ، نصائح في السياحة والسفر ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (5, N'تصميم فيديو', N'تصميم فيديو.png', N'تصميم انترو ، صور متحركة ، موشن جرافيك ، مونتاج فيديو ، وايت بورد ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (6, N'تصميم', N'تصميم.png', N'اغلفة كتب ومجلات ، بانرات اعلانية ، بطاقة عمل ، تيشرتات ، شعار ، عروض تقديمية ، معماري وديكور ،
خدمات تعديل الصور ، رسوم كارتونية ، أخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (7, N'صوتيات', N'صوتيات.jpg', N'انتاج كتب صوتية ، المعالجات الصوتية ، تحرير بودكاست ، تعليق صوتي ، أخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (8, N'كتابة وترجمة', N'كتابة.webp', N'الكتابة الابداعية ، تفريغ نصوص ، خدمات تدقيق لغوي ، خدمات ترجمة ، خدمات تلخيص ، كتابة السيرة الذاتية ، كتابة النصوص الاعلانية ، كتابة سيناريو ، كتابة محتوى متخصص ، كتابة محتوى مواقع ، كتابة مقالات ومراجعات ، أخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (9, N'حفلات ومناسبات ', N'حفلات ومناسبات.jpg', N'مصور فوتوغرافي ، شيف حفلات ، عازف الات موسيقية ، مغني حفلات ، حفلات أطفال وعرائس ، حجز قاعات أفراح ، منسق حفلات ، أخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (10, N'أعمال و مهن حرة', N'مهن حرة.jpg', N'أعمال نجارة ، أعمال سباكة ، أعمال كهرباء ، أعمال تركيبات ، أعمال نظافة ، أعمال صيانة ، أعمال خدمة منزلية ، أعمال طبية وتمريض ، أعمال نقاشة ، أخرى ')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (11, N'أعمال فنية ومصنوعات يدوية', N'اعمال فنية.jpg', N'رسم بورتريه ، رسم جداريات ، رسم تجريدي ، تطريز ، خياطة ، كروشيه ، تريكو ، اخرى')
INSERT INTO [dbo].[Categories] ([CategoryId], [Name], [CategoryImg], [Description]) VALUES (12, N'خدمات أخرى', N'خدمات-اخرى-1.png', N'اذا لما تجد أي قسم يناسب الخدمة التي تود البحث عنها ستجده هنا في خدمات اخرى')
SET IDENTITY_INSERT [dbo].[Categories] OFF
